### ISSUE TITLE
/in no longer functions at least in 8.2.5

### ISSUE THREAD

**Issue by Malholis** [funkydude/SlashIn#2]
I am unable to use /in commands in my macros. I get 'Interface action failed because of an AddOn' on even simple commands such as "/in 3 /say Hello"

Is this a potential fix or has /in been killed by WoW updates to no longer function?

**Comment by funkydude** [comment]
Hi.
SlashIn still works fine.
Unfortunately addons can no longer use /say outside of dungeons and raids.
For example:
```/in 5 /emote hi```
Will work just fine.
