### ISSUE TITLE
'SlashIn' tried to call the protected function 'UNKNOWN()'.

### ISSUE THREAD

**Issue by zmoose** [funkydude/SlashIn#5]
Saw this today:
1x [ADDON_ACTION_BLOCKED] AddOn 'SlashIn' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@FrameXML\ChatFrame.lua"]:4547: in function <FrameXML\ChatFrame.lua:4522>
[string "=[C]"]: ?
[string "=[C]"]: in function `xpcall'
[string "@SlashIn\SlashIn-v8.3.0.lua"]:15: in function <SlashIn\SlashIn.lua:13>
[string "@SlashIn\SlashIn-v8.3.0.lua"]:34: in function <SlashIn\SlashIn.lua:34>

**Comment by funkydude** [comment]
Addons can no longer use /say or /yell outside of dungeons and raids.
For example:
/in 5 /emote hi
Will work just fine.

**Comment by zmoose** [comment]
Thanks for the info!
