### ISSUE TITLE
SlashIn' tried to call the protected function 'UNKNOWN()'

### ISSUE THREAD

**Issue by zmoose** [funkydude/SlashIn#6]
1x [ADDON_ACTION_BLOCKED] AddOn 'SlashIn' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@FrameXML\ChatFrame.lua"]:4761: in function <FrameXML\ChatFrame.lua:4736>
[string "=[C]"]: ?
[string "=[C]"]: in function `xpcall'
[string "@SlashIn\SlashIn-v9.0.0.lua"]:15: in function <SlashIn\SlashIn.lua:13>
[string "@SlashIn\SlashIn-v9.0.0.lua"]:34: in function <SlashIn\SlashIn.lua:34>

**Comment by funkydude** [comment]
As per the addon description, this error usually happens when you try to run code that addons are not allowed to run.

What were you trying to run?

**Comment by zmoose** [comment]
I'm using the same macros I used in BFA that used to work.

```
#showtooltip Guardian of Ancient Kings
/cast Guardian of Ancient Kings
/y *** Guardian of Ancient Kings UP ***
/dbm timer 8 Guardian of Ancient Kings
/in 8 /y *** Guardian of Ancient Kings DOWN ***
```

```
#showtooltip Blessing of Sacrifice
/cast Blessing of Sacrifice
/y *** Blessing of Sacrifice UP ***
/dbm timer 12 Blessing of Sacrifice
/in 12 /y *** Blessing of Sacrifice DOWN ***
```

```
#showtooltip Ardent Defender
/cast Ardent Defender
/y *** Ardent Defender UP ***
/dbm timer 8 Ardent Defender
/in 8 /y *** Ardent Defender DOWN ***
```

When the /in time expires and I expect it to display the message to chat my chat window instead shows:
[13:12:19] [Y] [50:Palaclysm]: *** Ardent Defender UP ***
[13:12:27] Interface action failed because of an AddOn

**Comment by funkydude** [comment]
Yell & Say hasn't been possible to automate in quite a long time. It's only possible in raids and dungeons.
The only replacement is `/emote` or other group-type chats

**Comment by zmoose** [comment]
Alright I'll change my macro. Thanks!
