### ISSUE TITLE
follow macro fails 

### ISSUE THREAD

**Issue by Walkerbo** [funkydude/SlashIn#8]
## Describe the problem
My follow macro no longer works.
It used to mount and then target a named player then after 1.8 seconds follow.

```
/cleartarget
/use Jeweled Onyx Panther
/tar [exists][nodead]Astirral
/tar [exists][nodead]Leelee
/tar [exists][nodead]Imitatia
/tar [exists][nodead]Evellarize
/tar [exists][nodead]Luminize
/tar [exists][nodead]Timtam
/tar [exists][nodead]Priestice
/tar [exists][nodead]Frostangel
/tar [exists][nodead]Evilarise
/in 1.8 /follow
```

### What steps will reproduce the problem?

1.  Create the above macro
2.  Substitute names for players that you know
3.  Click macro when in range

### What version of the addon are you using? (Stating 'latest' is not useful)
SlashIn-v10.0.1.zip

### Do you have an error log of what happened?
```
1x [ADDON_ACTION_BLOCKED] AddOn 'SlashIn' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@FrameXML/ChatFrame.lua"]:4912: in function <FrameXML/ChatFrame.lua:4887>
[string "=[C]"]: in function `xpcall'
[string "@SlashIn/SlashIn.lua"]:15: in function <SlashIn/SlashIn.lua:13>
[string "@SlashIn/SlashIn.lua"]:32: in function <SlashIn/SlashIn.lua:32>
```

**Comment by funkydude** [comment]
When did you last try this and it was working?

**Comment by Walkerbo** [comment]
Pre dragonflight this was working properly for me.

**Comment by funkydude** [comment]
If the last time you tested this was pre-dragonflight, then this is most likely intentional breakage by Blizzard.
